### PR TITLE
Adding in regex for warning

### PR DESCRIPTION
**Pull request by Elaniobro**
@jasjuang Updating using same linting policy as eslint to allow for 'severity': 'warning' and yellow highlihting. #3  & #2

### CODE REVIEW

**Comment by jasjuang** [comment]
Hey @Elaniobro Thanks for the contribution but the change you applied doesn't work. Please use [Regex101](https://regex101.com/) to verify the correctness of the regex. I tried it on a simple error message from lesshint like

`Warning: index.less: line 6, col 5, duplicateProperty: Duplicate property: "width".`

I also verified by using your branch and it doesn't work.

**Comment by Elaniobro** [comment]
Sorry @jasjuang was not that familiar with that tool. Thanks so much for sharing, it is wicked cool!!!

I am also new to python, so that was my initial stab at it. I have since tested both the regex pattern and the plugin locally. https://regex101.com/r/LFZGBw/1/

**Comment by jasjuang** [comment]
@Elaniobro Thanks for the contribution but you forgot to add a pair of `()` so it only works for

`Warning: index.less: line 6, col 5, duplicateProperty: Duplicate property: "width".`

but not 

`Error: index.less: line 6, col 5, duplicateProperty: Duplicate property: "width".`

I updated https://regex101.com/r/LFZGBw/2/ so please see it for details. Please update and give it a try and verify it also works on your end.

**Comment by jasjuang** [comment]
Thank you for your contribution!

**Pull request merged**
